version: '3.8'

services:
  rag-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: rag-app-dev
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=ragdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - WEAVIATE_URL=http://weaviate:8080
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ./uploads:/app/uploads
      - ./models:/app/models
      - maven_cache:/root/.m2
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rag-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: rag-postgres-dev
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - rag-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ragdb"]
      interval: 30s
      timeout: 10s
      retries: 3

  weaviate:
    image: semitechnologies/weaviate:1.22.4
    container_name: rag-weaviate-dev
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    ports:
      - "8081:8080"
    volumes:
      - weaviate_dev_data:/var/lib/weaviate
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/meta"]
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer:latest
    container_name: rag-adminer-dev
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - rag-network

volumes:
  postgres_dev_data:
  weaviate_dev_data:
  maven_cache:

networks:
  rag-network:
    driver: bridge